on: pull_request_target
jobs:
 linux:
    uses: minecraft-linux/appimage-builder/.github/workflows/main.yml@main
    with:
      submodule-refs: |-
        [
          {
            "project": "mcpelauncher",
            "path": "mcpelauncher-client",
            "ref": ${{ tojson(github.event.pull_request.head.sha || github.sha) }}
          }
        ]
 macOS:
    uses: minecraft-linux/macos-builder/.github/workflows/main.yml@main
    with:
      submodule-refs: |-
        [
          {
            "project": "mcpelauncher",
            "path": "mcpelauncher-client",
            "ref": ${{ tojson(github.event.pull_request.head.sha || github.sha) }}
          }
        ]
    secrets: inherit
